<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Inventory;
use App\Models\User;

class InventorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get or create a petani user
        $petani = User::firstOrCreate(
            ['email' => 'petani@kato.com'],
            [
                'name' => 'Petani Kato',
                'password' => bcrypt('password'),
                'phone' => '081234567892',
                'address' => 'Jawa Tengah, Indonesia',
                'user_type' => 'petani',
                'is_verified' => true,
                'verified_at' => now(),
            ]
        );

        // Create inventory items for bubuk umbi-umbian
        $inventoryItems = [
            [
                'user_id' => $petani->id,
                'product_name' => 'Bubuk Tepung Bayam Organik',
                'description' => 'Bubuk tepung bayam organik kaya nutrisi, tinggi zat besi dan vitamin A. Diolah dengan teknologi modern untuk menjaga kandungan nutrisi alami.',
                'category' => 'Sayuran',
                'subcategory' => 'Bayam',
                'quantity' => 50.0,
                'unit' => 'kg',
                'price_per_unit' => 45000,
                'original_price' => 55000,
                'discount_percentage' => 18.18,
                'rating' => 4.8,
                'review_count' => 245,
                'is_featured' => true,
                'harvest_date' => now()->subDays(5),
                'estimated_ready_date' => now()->addDays(2),
                'packaging_type' => 'Plastik',
                'delivery_method' => 'Pickup',
                'season' => 'Kemarau',
                'photos' => ['assets/images/bayam_powder.jpg'],
                'status' => 'available',
                'notes' => 'Bubuk bayam organik kaya nutrisi, tinggi zat besi dan vitamin A',
            ],
            [
                'user_id' => $petani->id,
                'product_name' => 'Bubuk Jahe Premium',
                'description' => 'Bubuk jahe premium dengan aroma dan rasa yang kuat. Diolah dari jahe segar pilihan untuk memberikan khasiat maksimal.',
                'category' => 'Rempah',
                'subcategory' => 'Jahe',
                'quantity' => 75.0,
                'unit' => 'kg',
                'price_per_unit' => 35000,
                'original_price' => 40000,
                'discount_percentage' => 12.5,
                'rating' => 4.6,
                'review_count' => 189,
                'is_featured' => false,
                'harvest_date' => now()->subDays(3),
                'estimated_ready_date' => now()->addDays(1),
                'packaging_type' => 'Plastik',
                'delivery_method' => 'Pickup',
                'season' => 'Kemarau',
                'photos' => ['assets/images/jahe_powder.jpg'],
                'status' => 'available',
                'notes' => 'Bubuk jahe asli dengan khasiat menghangatkan tubuh dan meningkatkan imunitas',
            ],
            [
                'user_id' => $petani->id,
                'product_name' => 'Bubuk Labu Kuning Organik',
                'description' => 'Bubuk labu kuning organik kaya beta-karoten dan serat untuk kesehatan mata. Diolah dari labu kuning segar tanpa bahan pengawet.',
                'category' => 'Umbi',
                'subcategory' => 'Labu',
                'quantity' => 25.0,
                'unit' => 'kg',
                'price_per_unit' => 65000,
                'original_price' => 80000,
                'discount_percentage' => 18.75,
                'rating' => 4.9,
                'review_count' => 156,
                'is_featured' => true,
                'harvest_date' => now()->subDays(7),
                'estimated_ready_date' => now()->addDays(3),
                'packaging_type' => 'Plastik',
                'delivery_method' => 'Pickup',
                'season' => 'Kemarau',
                'photos' => ['assets/images/labu_powder.jpg'],
                'status' => 'available',
                'notes' => 'Bubuk labu kuning organik kaya beta-karoten dan serat untuk kesehatan mata',
            ],
            [
                'user_id' => $petani->id,
                'product_name' => 'Bubuk Ubi Jalar Ungu',
                'description' => 'Bubuk ubi jalar ungu premium dengan antosianin tinggi untuk anti-aging. Diolah dari ubi jalar ungu organik pilihan.',
                'category' => 'Umbi',
                'subcategory' => 'Ubi Jalar',
                'quantity' => 40.0,
                'unit' => 'kg',
                'price_per_unit' => 55000,
                'original_price' => 65000,
                'discount_percentage' => 15.38,
                'rating' => 4.7,
                'review_count' => 203,
                'is_featured' => false,
                'harvest_date' => now()->subDays(4),
                'estimated_ready_date' => now()->addDays(2),
                'packaging_type' => 'Plastik',
                'delivery_method' => 'Pickup',
                'season' => 'Kemarau',
                'photos' => ['assets/images/ubi_ungu_powder.jpg'],
                'status' => 'available',
                'notes' => 'Bubuk ubi jalar ungu premium dengan antosianin tinggi untuk anti-aging',
            ],
            [
                'user_id' => $petani->id,
                'product_name' => 'Bubuk Kunyit Asli',
                'description' => 'Bubuk kunyit asli dengan kurkumin tinggi untuk anti-inflamasi dan antioksidan. Diolah dari kunyit segar tanpa campuran.',
                'category' => 'Rempah',
                'subcategory' => 'Kunyit',
                'quantity' => 60.0,
                'unit' => 'kg',
                'price_per_unit' => 75000,
                'original_price' => 90000,
                'discount_percentage' => 16.67,
                'rating' => 4.9,
                'review_count' => 312,
                'is_featured' => true,
                'harvest_date' => now()->subDays(6),
                'estimated_ready_date' => now()->addDays(1),
                'packaging_type' => 'Plastik',
                'delivery_method' => 'Pickup',
                'season' => 'Kemarau',
                'photos' => ['assets/images/kunyit_powder.jpg'],
                'status' => 'available',
                'notes' => 'Bubuk kunyit asli dengan kurkumin tinggi untuk anti-inflamasi dan antioksidan',
            ],
            [
                'user_id' => $petani->id,
                'product_name' => 'Bubuk Temulawak Premium',
                'description' => 'Bubuk temulawak premium untuk kesehatan hati dan pencernaan. Diolah dari temulawak segar dengan standar farmasi.',
                'category' => 'Rempah',
                'subcategory' => 'Temulawak',
                'quantity' => 35.0,
                'unit' => 'kg',
                'price_per_unit' => 100000,
                'original_price' => 120000,
                'discount_percentage' => 16.67,
                'rating' => 4.8,
                'review_count' => 178,
                'is_featured' => false,
                'harvest_date' => now()->subDays(8),
                'estimated_ready_date' => now()->addDays(4),
                'packaging_type' => 'Plastik',
                'delivery_method' => 'Pickup',
                'season' => 'Kemarau',
                'photos' => ['assets/images/temulawak_powder.jpg'],
                'status' => 'available',
                'notes' => 'Bubuk temulawak premium untuk kesehatan hati dan pencernaan',
            ],
            [
                'user_id' => $petani->id,
                'product_name' => 'Bubuk Wortel Organik',
                'description' => 'Bubuk wortel organik kaya vitamin A dan beta-karoten untuk kesehatan mata. Diolah dari wortel segar tanpa pestisida.',
                'category' => 'Sayuran',
                'subcategory' => 'Wortel',
                'quantity' => 45.0,
                'unit' => 'kg',
                'price_per_unit' => 40000,
                'original_price' => 50000,
                'discount_percentage' => 20.0,
                'rating' => 4.5,
                'review_count' => 134,
                'is_featured' => false,
                'harvest_date' => now()->subDays(2),
                'estimated_ready_date' => now()->addDays(1),
                'packaging_type' => 'Plastik',
                'delivery_method' => 'Pickup',
                'season' => 'Kemarau',
                'photos' => ['assets/images/wortel_powder.jpg'],
                'status' => 'available',
                'notes' => 'Bubuk wortel organik kaya vitamin A dan beta-karoten untuk kesehatan mata',
            ],
            [
                'user_id' => $petani->id,
                'product_name' => 'Bubuk Brokoli Organik',
                'description' => 'Bubuk brokoli organik kaya vitamin C dan antioksidan. Diolah dari brokoli segar untuk menjaga nutrisi alami.',
                'category' => 'Sayuran',
                'subcategory' => 'Brokoli',
                'quantity' => 30.0,
                'unit' => 'kg',
                'price_per_unit' => 60000,
                'original_price' => 75000,
                'discount_percentage' => 20.0,
                'rating' => 4.6,
                'review_count' => 98,
                'is_featured' => false,
                'harvest_date' => now()->subDays(1),
                'estimated_ready_date' => now()->addDays(2),
                'packaging_type' => 'Plastik',
                'delivery_method' => 'Pickup',
                'season' => 'Kemarau',
                'photos' => ['assets/images/brokoli_powder.jpg'],
                'status' => 'available',
                'notes' => 'Bubuk brokoli organik kaya vitamin C dan antioksidan',
            ],
        ];

        foreach ($inventoryItems as $item) {
            Inventory::create($item);
        }
    }
}