version: '3.8'

services:
  backend:
    build: .
    container_name: kato-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://backend-kato.throoner.my.id
      - DB_CONNECTION=mysql
      - DB_HOST=kato-mysql
      - DB_PORT=3306
      - DB_DATABASE=kato-app
      - DB_USERNAME=kato_user
      - DB_PASSWORD=kato_password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=file
      - REDIS_HOST=kato-redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "
        php artisan key:generate --force &&
        php artisan migrate --force &&
        php artisan config:cache &&
        php artisan route:cache &&
        php artisan serve --host=0.0.0.0 --port=8000
      "

  mysql:
    image: mysql:8.0
    container_name: kato-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=kato-app
      - MYSQL_USER=kato_user
      - MYSQL_PASSWORD=kato_password
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "kato_user", "-pkato_password"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: kato-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
