[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --optimize-autoloader"]

[phases.build]
cmds = ["php artisan migrate --force", "php artisan db:seed --force"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"