name: kato-backend
services:
- name: web
  source_dir: /
  github:
    repo: Yafigg/backend-kato-app
    branch: main
  run_command: php -S 0.0.0.0:8080 -t public
  environment_slug: php
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /api/health
  envs:
  - key: APP_ENV
    value: production
  - key: APP_DEBUG
    value: false
  - key: LOG_LEVEL
    value: error
  - key: DB_CONNECTION
    value: pgsql
  - key: CACHE_DRIVER
    value: file
  - key: SESSION_DRIVER
    value: file
  - key: QUEUE_CONNECTION
    value: sync
